---
- name: Set facts for Master without Sample Content
  set_fact:
    magento_sample_content: 'no'
  when: magento_reach_dropdown == 'Fresh install of the latest Magento CE 1.9.x release'

- name: Set facts for Master with Sample Content
  set_fact:
    magento_sample_content: 'True'
  when: magento_reach_dropdown == 'Fresh install of the latest Magento CE 1.9.x release (including sample data)'

- include: configure_common.yml
- include: install_master.yml