---
- name: Download Magento
  get_url:
    url: '{{ magento_download_path }}{{ magento_file_name }}'
    dest: '{{ magento_document_root }}'
    owner: 'www-data'
    group: 'www-data'
    validate_certs: no

- name: Download Sample Content
  get_url:
    url: '{{ magento_download_path }}{{ magento_sample_file_name }}'
    dest: '{{ magento_document_root }}'
    owner: 'www-data'
    group: 'www-data'
    validate_certs: no
  when: magento_sample_content == 'True'

- name: Unpack Magento
  unarchive:
    src: '{{ magento_document_root }}/{{ magento_file_name }}'
    dest: '{{ magento_document_root }}'
    owner: 'www-data'
    group: 'www-data'
    copy: no

- name: Unpack Sample Content
  unarchive:
    src: '{{ magento_document_root }}/{{ magento_sample_file_name }}'
    dest: '{{ magento_document_root }}'
    owner: 'www-data'
    group: 'www-data'
    copy: no
  when: magento_sample_content == 'True'

- name: Download 'Magento Sample Version' file
  get_url:
    url: '{{ magento_download_path }}sample_content_version.txt'
    dest: '{{ magento_document_root }}'
    owner: 'www-data'
    group: 'www-data'

- name: Get Sample Data Version
  command:
    'cat sample_content_version.txt'
  args:
    chdir: '{{ magento_document_root }}'
  register: magento_sample_content_version

- name: Copy Core Files
  shell:
    'cp -R {{ magento_document_root }}/magento/{{ item }} {{ magento_document_root }}/'
  args:
    chdir: '{{ magento_document_root }}'
  with_items:
    - '*'
    - '.htaccess'

- name: Change chown
  shell:
    'chown -R www-data:www-data {{ magento_document_root }}/{{ item }}'
  args:
    chdir: '{{ magento_document_root }}'
  with_items:
    - '*'
    - '.htaccess'

